
version: '3.1'

services:
  
  adminer:
    image: adminer
    container_name: adminer_teste
    ports:
      - 8080:8080


  mysql-db:
    image: mysql:8.0
    container_name: mysql_teste
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: imoveis_db 
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3310:3306"
    cap_add:
      - SYS_NICE