# Generated by Django 4.0.5 on 2022-06-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='adress',
            old_name='endereço',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='adress',
            old_name='número',
            new_name='numero',
        ),
    ]
