# Generated by Django 4.0.5 on 2022-06-26 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_adress_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='cep',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d\\d\\d\\d\\d\\d\\d\\d$', message='Insira um CEP válido')]),
        ),
    ]
