# Generated by Django 4.0.5 on 2022-06-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_adress_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='cep',
            field=models.CharField(max_length=10),
        ),
    ]
